{% set name = "modulegraph2" %}
{% set version = "2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/modulegraph2-{{ version }}.tar.gz
  sha256: ea7a32c74801da05815897b4aa43aa278e38380bc6f65d81205239e54c1f85ad

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - flit
  run:
    - objectgraph
    - python
    - typing_extensions

test:
  imports:
    - modulegraph2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://modulegraph2.readthedocs.io/
  summary: A module import dependency graph for Python projects.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
