{% set name = "modulegraph2" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/modulegraph2-{{ version }}.tar.gz
  sha256: 1f0f7816cd6640d157573856b5929e12215dc6804a58ec777f77df9dfd018f2e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit
  run:
    - objectgraph
    - python >={{ python_min }},<4
    - typing_extensions

test:
  imports:
    - modulegraph2
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://modulegraph2.readthedocs.io/
  summary: A module import dependency graph for Python projects.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
