{% set name = "modulegraph2" %}
{% set version = "2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/modulegraph2-{{ version }}.tar.gz
  sha256: 6452aa294e3a1fb4d0d6faca2ef0879e2fa2c23a135a5a202d08db3518d44fcc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4
    - flit
  run:
    - objectgraph
    - python >=3.6,<4
    - typing_extensions

test:
  imports:
    - modulegraph2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://modulegraph2.readthedocs.io/
  summary: A module import dependency graph for Python projects.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nehaljwani
